"use strict";
export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';
export const USER_MENU_CLICK = 'USER_MENU_CLICK';
export const USER_MENU_HIDE = 'USER_MENU_HIDE';
