"use strict";
export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';
export const USER_MENU_CLICK = 'USER_MENU_CLICK';
export const CLICK_FILE_BOX = 'CLICK_FILE_BOX';
export const CLICK_PEOPLE_BOX = 'CLICK_PEOPLE_BOX';
export const ALL_HIDE = 'ALL_HIDE';
export const ADD_DIALOGUE = 'ADD_DIALOGUE';
//删除对话成员
export const DELETE_THE_CONVERSATION_MEMBER = 'DELETE_THE_CONVERSATION_MEMBER';
//新增对话
export const ADD_CHAT = 'ADD_CHAT';
