"use strict";
export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';
export const USER_MENU_CLICK = 'USER_MENU_CLICK';
export const CLICK_FILE_BOX = 'CLICK_FILE_BOX';
export const CLICK_PEOPLE_BOX = 'CLICK_PEOPLE_BOX';
export const ALL_HIDE = 'ALL_HIDE';
export const ADD_DIALOGUE = 'ADD_DIALOGUE';
